import * as features from './features';
import * as permission from './permission';
import * as roles from './roles';
import * as department from './department';
import * as userTags from './user-tags';

const GRAPH_QL_SCHEMAS = {
  PERMISSIONS: {
    QUERY: {
      GQL_QUERY_PERMISSIONS: permission.GQL_QUERY_PERMISSIONS,
      GQL_QUERY_SINGLE_PERMISSION: permission.GQL_QUERY_SINGLE_PERMISSION,
      GQL_QUERY_ALL_DELETE_PERMISSION: permission.GQL_QUERY_ALL_DELETE_PERMISSION
    },
    MUTATION: {
      GQL_MUTATION_CREATE_PERMISSION: permission.GQL_MUTATION_CREATE_PERMISSION,
      GQL_MUTATION_UPDATE_PERMISSION: permission.GQL_MUTATION_UPDATE_PERMISSION,
      GQL_MUTATION_UPDATE_STATUS_PERMISSION: permission.GQL_MUTATION_UPDATE_STATUS_PERMISSION,
      GQL_MUTATION_DELETE_PERMISSION: permission.GQL_MUTATION_DELETE_PERMISSION,
      GQL_MUTATION_RESTORE_DELETE_PERMISSION: permission.GQL_MUTATION_RESTORE_DELETE_PERMISSION,
      GQL_MUTATION_PERMANENT_DELETE_PERMISSION: permission.GQL_MUTATION_PERMANENT_DELETE_PERMISSION
    }
  },
  FEATURES: {
    QUERY: {
      GQL_QUERY_ALL_FEATURES: features.GQL_QUERY_ALL_FEATURES,
      GQL_QUERY_SINGLE_FEATURES: features.GQL_QUERY_SINGLE_FEATURES
    },
    MUTATION: {
      GQL_MUTATION_CREATE_FEATURE: features.GQL_MUTATION_CREATE_FEATURE,
      GQL_MUTATION_UPDATE_FEATURE: features.GQL_MUTATION_UPDATE_FEATURE,
      GQL_MUTATION_PERMANENTLY_DELETE_FEATURE: features.GQL_MUTATION_PERMANENTLY_DELETE_FEATURE
    }
  },
  ROLES: {
    QUERY: {
      GQL_QUERY_ROLES: roles.GQL_QUERY_ROLES,
      GQL_QUERY_ACCESS_CONTROL: roles.GQL_QUERY_ACCESS_CONTROL,
      GQL_QUERY_SINGLE_ROLES: roles.GQL_QUERY_SINGLE_ROLES,
      GQL_QUERY_DELETE_ROLES: roles.GQL_QUERY_DELETE_ROLES
    },
    MUTATION: {
      GQL_MUTATION_CREATE_ROLES: roles.GQL_MUTATION_CREATE_ROLES,
      GQL_MUTATION_UPDATE_ROLES: roles.GQL_MUTATION_UPDATE_ROLES,
      GQL_MUTATION_UPDATE_STATUS_ROLES: roles.GQL_MUTATION_UPDATE_STATUS_ROLES,
      GQL_MUTATION_TEMPORARY_DELETE_ROLES: roles.GQL_MUTATION_TEMPORARY_DELETE_ROLES,
      GQL_MUTATION_RESTORE_DELETE_ROLE: roles.GQL_MUTATION_RESTORE_DELETE_ROLE,
      GQL_MUTATION_PERMANENTLY_DELETE_ROLE: roles.GQL_MUTATION_PERMANENTLY_DELETE_ROLE
    }
  },
  DEPARTMENT: {
    QUERY: {
      GQL_QUERY_ALL_DEPARTMENTS: department.GQL_QUERY_ALL_DEPARTMENTS,
      GQL_QUERY_SINGLE_DEPARTMENT: department.GQL_QUERY_SINGLE_DEPARTMENT
    },
    MUTATION: {
      GQL_MUTATION_CREATE_DEPARTMENTS: department.GQL_MUTATION_CREATE_DEPARTMENTS,
      GQL_MUTATION_UPDATE_DEPARTMENTS: department.GQL_MUTATION_UPDATE_DEPARTMENTS,
      GQL_MUTATION_UPDATE_STATUS_DEPARTMENTS: department.GQL_MUTATION_UPDATE_STATUS_DEPARTMENTS,
      GQL_MUTATION_PERMANENTLY_DELETE_DEPARTMENTS:
        department.GQL_MUTATION_PERMANENTLY_DELETE_DEPARTMENTS
    }
  },
  USER_TAGS: {
    QUERY: {
      GQL_QUERY_ALL_USER_TAGS: userTags.GQL_QUERY_ALL_USER_TAGS,
      GQL_QUERY_SINGLE_USER_TAGS: userTags.GQL_QUERY_SINGLE_USER_TAGS
    },
    MUTATION: {
      GQL_MUTATION_CREATE_USER_TAGS: userTags.GQL_MUTATION_CREATE_USER_TAGS,
      GQL_MUTATION_UPDATE_USER_TAGS: userTags.GQL_MUTATION_UPDATE_USER_TAGS,
      GQL_MUTATION_UPDATE_STATUS_USER_TAGS: userTags.GQL_MUTATION_UPDATE_STATUS_USER_TAGS,
      GQL_MUTATION_PERMANENTLY_DELETE_USER_TAGS: userTags.GQL_MUTATION_PERMANENTLY_DELETE_USER_TAGS
    }
  }
};

export default GRAPH_QL_SCHEMAS;
