import type { Metadata } from 'next';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { geistMono, geistSans } from './fonts';
import AdminLayout from '@/components/layout/AdminLayout';
import TopLoadingBar from '@/components/custom/loader/top-loading-bar';
import GraphQlProvider from '@/components/provider/graph-ql';
import { Toaster } from "@/components/ui/toaster"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TopLoadingBar>
            <GraphQlProvider>
              <AdminLayout>{children}</AdminLayout>
              <Toaster />
            </GraphQlProvider>
          </TopLoadingBar>
        </ThemeProvider>
      </body>
    </html>
  );
}
