import * as DepartmentApi from './department';
import * as FeatureApi from './features';
import * as PermissionApi from './permission';
import * as RolesApi from './roles';
import * as UserTagsAPi from './user-tags';

const BACKEND_APIS = {
  PERMISSIONS: {
    API_GET_PERMISSIONS: PermissionApi.API_GET_PERMISSIONS,
    API_GET_PERMISSION: PermissionApi.API_GET_PERMISSION,
    API_CREATE_PERMISSION: PermissionApi.API_CREATE_PERMISSION,
    API_UPDATE_PERMISSION: PermissionApi.API_UPDATE_PERMISSION,
    API_UPDATE_STATUS_PERMISSION: PermissionApi.API_UPDATE_STATUS_PERMISSION,
    API_DELETE_PERMISSION: PermissionApi.API_DELETE_PERMISSION,
    API_TEMP_DELETE_PERMISSION_LIST: PermissionApi.API_TEMP_DELETE_PERMISSION_LIST,
    API_RESTORE_PERMISSIONS: PermissionApi.API_RESTORE_PERMISSIONS,
    API_PERMANENT_DELETE_PERMISSIONS: PermissionApi.API_PERMANENT_DELETE_PERMISSIONS
  },
  FEATURES: {
    API_GET_ALL_FEATURES: FeatureApi.API_GET_ALL_FEATURES,
    API_GET_SINGLE_FEATURE: FeatureApi.API_GET_SINGLE_FEATURE,
    API_CREATE_FEATURE: FeatureApi.API_CREATE_FEATURE,
    API_UPDATE_FEATURE: FeatureApi.API_UPDATE_FEATURE,
    API_PERMANENT_DELETE_FEATURES: FeatureApi.API_PERMANENT_DELETE_FEATURES
  },
  ROLES: {
    API_GET_ROLES_ACCESS_CONTROL: RolesApi.API_GET_ROLES_ACCESS_CONTROL,
    API_GET_ALL_ROLES: RolesApi.API_GET_ALL_ROLES,
    API_GET_SINGLE_ROLES: RolesApi.API_GET_SINGLE_ROLES,
    API_CREATE_ROLES: RolesApi.API_CREATE_ROLES,
    API_UPDATE_ROLES: RolesApi.API_UPDATE_ROLES,
    API_UPDATE_STATUS_ROLES: RolesApi.API_UPDATE_STATUS_ROLES,
    API_TEMPORARY_DELETE_ROLES: RolesApi.API_TEMPORARY_DELETE_ROLES,
    API_GET_ALL_DELETE_ROLES: RolesApi.API_GET_ALL_DELETE_ROLES,
    API_RESTORE_ROLES: RolesApi.API_RESTORE_ROLES,
    API_PERMANENTLY_DELETE_ROLE: RolesApi.API_PERMANENTLY_DELETE_ROLE
  },
  DEPARTMENT: {
    API_GET_ALL_DEPARTMENTS: DepartmentApi.API_GET_ALL_DEPARTMENTS,
    API_GET_SINGLE_DEPARTMENTS: DepartmentApi.API_GET_SINGLE_DEPARTMENTS,
    API_CREATE_DEPARTMENT: DepartmentApi.API_CREATE_DEPARTMENT,
    API_UPDATE_DEPARTMENT: DepartmentApi.API_UPDATE_DEPARTMENT,
    API_UPDATE_STATUS_DEPARTMENT: DepartmentApi.API_UPDATE_STATUS_DEPARTMENT,
    API_PERMANENT_DELETE_DEPARTMENT: DepartmentApi.API_PERMANENT_DELETE_DEPARTMENT
  },
  User_TAGS: {
    API_GET_ALL_USER_TAGS: UserTagsAPi.API_GET_ALL_USER_TAGS,
    API_GET_SINGLE_USER_TAGS: UserTagsAPi.API_GET_SINGLE_USER_TAGS,
    API_CREATE_USER_TAGS: UserTagsAPi.API_CREATE_USER_TAGS,
    API_UPDATE_USER_TAGS: UserTagsAPi.API_UPDATE_USER_TAGS,
    API_UPDATE_STATUS_USER_TAGS: UserTagsAPi.API_UPDATE_STATUS_USER_TAGS,
    API_PERMANENT_DELETE_USER_TAGS: UserTagsAPi.API_PERMANENT_DELETE_USER_TAGS
  }
};

export default BACKEND_APIS;
